import {createNotebook, createNote} from '@wix/quix-shared';
import {QuixFolder, ExamplesNotebook} from '../config';

const addNote = (id, name, content) => createNote('examples', {id, name, content, owner: QuixFolder.owner});

export default () => createNotebook([{
  id: QuixFolder.id,
  name: QuixFolder.name
}], {
  ...ExamplesNotebook,
  notes: [
    addNote('simple', 'Simple query', `-- Hit "Run" to execute the query

SELECT 
    shipdate
    , shipinstruct
    , shipmode
FROM tpch.sf1.lineitem
LIMIT 100

`
    ),
    addNote('params', 'Parameters', `/* AUTOGENERATED
$string_param:string=[Hello World!] $number_param:number=[100] $bool_param:boolean=[true] $date_param:datetime=[2019-05-06 00:00] $list_param:list:Option 1,Option 2,Option 3=[Option 1,Option 2] $option_param:option:Option 1,Option 2,Option 3=[Option 1]
AUTOGENERATED END */

-- Click the hamburger menu on the left to add or edit parameters
-- Use $<param name> as placeholders in your query, they will be replaced with actual values when the query is executed

SELECT 
    '$string_param' as string_value
    , '$number_param' as number_param
    , '$bool_param' as bool_param
    , '$date_param' as date_param
    , '$list_param' as list_param
    , '$option_param' as option_param
      
`
    ),
    addNote('start-stop-params', 'START_TIME and STOP_TIME', `/* AUTOGENERATED
$START_TIME $STOP_TIME
AUTOGENERATED END */

-- START_TIME and STOP_TIME are handy params that allow to quickly define a range of two days
-- Values of these params are reset to their defaults each time the note is opened
-- START_TIME defaults to current_date - 2 days
-- STOP_TIME defaults to current_date

SELECT 
    '$START_TIME' start
    , '$STOP_TIME' stop
    , current_date as "current_date"
    , localtimestamp as "localtimestamp"
WHERE current_date BETWEEN TIMESTAMP '$START_TIME' AND TIMESTAMP '$STOP_TIME';

`
    ),
    addNote( 'timeline', 'Timeline chart', `/* AUTOGENERATED
$schema:option:tpch.tiny,tpch.sf1=[tpch.sf1]
AUTOGENERATED END */

-- Include at least one date and one numeric column in the result to enable timeline charts
-- Hit "Run" and choose the "chart" option from the menu on the left

SELECT
    date_trunc('year', shipdate) shipyear
    , shipmode
    , sum(quantity) quantity
FROM $schema.lineitem
GROUP BY 1, 2
ORDER BY 1

`
    ),
    addNote('bar', 'Bar chart', `/* AUTOGENERATED
$schema:option:tpch.tiny,tpch.sf1=[tpch.sf1]
AUTOGENERATED END */

-- Include at least one string and one numeric column in the result to enable bar charts
-- Hit "Run" and choose the "chart" option from the menu on the left

SELECT
    shipmode
    , sum(quantity) quantity
FROM $schema.lineitem
GROUP BY 1
ORDER BY 1

`
    ),
    addNote('pie', 'Pie chart', `/* AUTOGENERATED
$schema:option:tpch.tiny,tpch.sf1=[tpch.sf1]
AUTOGENERATED END */

-- Include at least one string and one numeric column in the result to enable pie charts
-- Hit "Run" and choose the "pie" option from the menu on the left

SELECT
    shipmode
    , sum(quantity) quantity
FROM $schema.lineitem
GROUP BY 1
ORDER BY 1

`
    )
  ]
});
