name: Quix Frontend Build
on:
  pull_request:
  push:
jobs:
  node_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name : Build and Test
      working-directory: ./quix-frontend
      run: | 
        npm ci
        npm run build:ci
        npm test
