name: Quix Frontend Build
on:
  pull_request:
  push:
defaults:
  run:
    working-directory: ./quix-frontend
jobs:
  node_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name : Build and Test
      run: | 
        npm ci
        npm run build:ci
        npm test
