# This Workflow will publish Documentation on any push to master branch into 
# the documentation folder.
name: Quix Documentation Publish
on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'     
        required: true
        default: 'Publish'
  push:
    branches: ['master']
    paths:
    - 'documentation/**/*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.19.1'
    - run: npm install
      working-directory: 'documentation/website'
    - run: npm run build
      working-directory: 'documentation/website'
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: documentation/website/build/quix
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}