name: Quix Frontend Build
on:
  pull_request:
    paths:
    - 'quix-frontend/**'  
  push:
    paths:
    - 'quix-frontend/**'
jobs:
  node_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name : Build and Test
      working-directory: ./quix-frontend
      run: | 
        npm install
        npm run build:ci
        npm test
