name: TEST

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'     
        required: true
        default: 'TEST'

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        uses: actions/checkout@v2
      - name: Print github
        run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT:${{ github }}
